[WiP] Color.FromName System.Drawing plug
CosmosOS/Cosmos pull request #1522
Opened 2020-10-16 21:06 UTC by KM198912

Color.FromName Plug

2020-10-17 17:37 UTC, ascpixel commented on source/Cosmos.System2_Plugs/System/Drawing/ColorImpl.cs
> +                    throw new Exception("Color Name must be passed to FromName");
You should change the type of the thrown exception to ArgumentException, so it would be easier to catch that specific exception.

2020-10-18 13:05 UTC, quajak requested changes
The PR looks good, two minor nitpicks. Can you please remove the `break;` statements which are not needed and add a small test to the graphic kernel?

2020-10-18 14:26 UTC, KM198912 commented
> 
> 
> The PR looks good, two minor nitpicks. Can you please remove the `break;` statements which are not needed and add a small test to the graphic kernel?

removed the break; but i dont know how to edit a second file in existing PR to add the test @quajak

2020-10-18 15:31 UTC, quajak approved these changes

2020-10-18 15:31 UTC, merged