Add ATAPI driver
CosmosOS/Cosmos pull request #1779
Opened 2021-05-20 21:26 UTC by MishaTY

Adds a basic ATAPI driver.

TODO
- [ ] Testing on real hardware
- [ ] Test on QEMU
- [ ] Test on Bochs

2021-05-20 21:28 UTC, MishaTY commented on source/Cosmos.HAL2/BlockDevice/IDE.cs
> +                Ata.AtaDebugger.Send("ATA device with speclevel ATAPI found");
Should we add the ATAPI to the BlockDevices array?

2021-05-20 21:56 UTC, charlesbetros requested changes
Please add the comments back. Especially when a type is public

2021-05-20 22:41 UTC, MishaTY commented
I can't test on real hardware because the dvd drive nor the hard drive is not showing up in the Blockdevice.Devices

2021-06-03 23:27 UTC, Arawn-Davies commented
@charlesbetros have you tested on real hardware or can I do it? been meaning to set up a real debugging host and this seems perfect for it!

2021-06-04 00:47 UTC, charlesbetros commented
I haven't tested real hardware. Not too concerned with that though. Feel free to test it.

I would like Atapio and Atapi to both inherit the ATA base class though before merging. They share a lot of code and constants and IO ports. The shared bits should be in the base class.

2021-06-05 20:31 UTC, Arawn-Davies commented
@charlesbetros ATAPI and AtaPio are both currently inheriting BlockDevice which is what at the end of the day the System2.FatFileSystem methods call to read specific sectors. C# doesn't have Multiple Inheritance like Perl so I'm not entirely sure whether to inherit Core.ATA, which is just an IOGroup with channel and controller stuff (Primary/Secondary,Master/Slave) with similar polling Wait() methods, or just keep as is

Both do have an ATA IOGroup instance of an object in each class, which I suppose is how the inheritance is done atm. I think for future USB XHCI block devices, best leave ATA code out of that can of worms 😂 :)

2021-06-05 23:23 UTC, Arawn-Davies commented
Personally I consider this ready to merge, but of course only when everyone's ok :)
This will need some TestRunner tests being done, but that could be done in a separate PR

2021-06-05 23:34 UTC, Arawn-Davies commented
Personally I consider this ready to merge, but of course only when everyone's ok :)
This will need some TestRunner tests being done, but that could be done in a separate PR

2021-06-05 23:58 UTC, charlesbetros commented
Sounds good. Merge away if it looks good. 

> On Jun 5, 2021, at 6:34 PM, Arawn Davies ***@***.***> wrote:
> 
> ﻿
> Personally I consider this ready to merge, but of course only when everyone's ok :)
> This will need some TestRunner tests being done, but that could be done in a separate PR
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-06 11:20 UTC, Arawn-Davies approved these changes
XML comments have been added back in the latest commit. All good to go!

2021-06-06 11:22 UTC, Arawn-Davies commented
> Sounds good. Merge away if it looks good.
think you need to finish your review, can't merge :)

2021-06-08 15:24 UTC, charlesbetros approved these changes

2021-06-08 16:11 UTC, merged

2021-06-08 16:13 UTC, MishaTY commented
That was github, did not mean to merge.

2021-06-08 16:15 UTC, quajak commented
Was there something left to do?

2021-06-08 16:18 UTC, MishaTY commented
Never mind, I thought that github dismissed the reviews, but @charlesbetros did.