FTP Implementation
CosmosOS/Cosmos pull request #1799
Opened 2021-06-02 12:22 UTC by valentinbreiz

2021-06-02 20:39 UTC, bad-codr commented
how i use

2021-06-03 09:10 UTC, valentinbreiz commented
When it will be ready @bad-codr ;)

2021-06-08 14:58 UTC, quajak approved these changes

2021-06-09 12:59 UTC, quajak requested changes

2021-06-09 12:59 UTC, quajak commented on source/Cosmos.System2/Network/IPv4/TCP/FTP/FtpServer.cs
> +                global::System.Console.WriteLine("Client : New connection from " + client.StateMachine.LocalAddress.ToString());
User should be able to disable this

2021-06-09 12:59 UTC, quajak commented on source/Cosmos.System2/Network/IPv4/TCP/FTP/FtpServer.cs
> +                global::System.Console.WriteLine("Client : " + data);
Same here. In future it would be best if we could use events to notify the OS that something happened but I dont know if they are currently supported

2021-06-09 13:58 UTC, quajak approved these changes

2021-06-09 15:22 UTC, merged