Implement FAT32 formatting
CosmosOS/Cosmos pull request #1832
Opened 2021-06-14 13:59 UTC by valentinbreiz

2021-06-17 17:36 UTC, quajak requested changes

2021-06-17 17:36 UTC, quajak commented on source/Cosmos.System2/FileSystem/CosmosVFS.cs
> +                var fs = FatFileSystem.CreateFatFileSystem(partition, id + ":\\", xSize);
Why arnt you checking `aDriveFormat` for the correct value? While currently there are no other possible values, this prevents us from having breaking changes in the future.

2021-06-20 12:15 UTC, MishaTY approved these changes

2021-06-20 14:50 UTC, MishaTY approved these changes

2021-06-21 08:37 UTC, quajak approved these changes

2021-06-21 08:37 UTC, merged