Fix PS2Mouse for Real Hardware
CosmosOS/Cosmos pull request #1837
Opened 2021-06-18 20:09 UTC by JuliusCaesar12

The mouse stopped working when a scroll wheel wasn't present.

2021-06-24 22:29 UTC, Arawn-Davies reviewed
Do you have a project I can use to test the changes? I just need something simple and lightweight - the code you used to test this would be ideal 👍🏽

2021-06-24 22:29 UTC, Arawn-Davies commented on source/Cosmos.HAL2/PS2Mouse.cs
> -                if (HasScrollWheel)
Why remove the check for a ScrollWheel?
Not every PS/2 mouse has one, so please put the checks back in place

2021-06-24 22:30 UTC, Arawn-Davies requested changes
Do you have a project I can use to test the changes? I just need something simple and lightweight - the code you used to test this would be ideal 👍🏽

We do need checks for the mousewheel, as not every PS/2 mouse has one, and there are differences between ps2 and imps2.

2021-06-25 19:07 UTC, JuliusCaesar12 commented
Re-adding the checks have made the mouse stay at the bottom both in the VM and on my laptop.

2021-06-25 20:25 UTC, JuliusCaesar12 commented
https://pastebin.com/Y5F709s0
This is a simple test kernel I created to test this (it only uses textmode, so it's not that intensive)

2021-07-23 09:03 UTC, quajak commented
Does it mean that we are incorrectly detecting mouse wheels?

2021-07-23 23:04 UTC, JuliusCaesar12 commented
> Does it mean that we are incorrectly detecting mouse wheels?

I'm not sure. I think it may have something to do with the fact that the trackpad is possibly a Synaptic pad.
I looked at the source code for ReactOS and looked at mouse.c; what I found was that the driver would only switch to finding the z movement if the device was not a generic ps2 device or a ps2pp device.

2021-07-24 11:18 UTC, quajak commented
Ok, I suppose we can do something similar. @Arawn-Davies @valentinbreiz @KM198912 thoughts?

2021-07-24 14:18 UTC, KM198912 commented
I think this could be done and synaptics issues I had before I think there is a push with that

2021-08-11 17:50 UTC, KM198912 commented
also i think we should make the disabling of that feature a optional user kernel setting since not everyone might have this issue and instead of completly disabling it we should see if we can find a reliable way to detect all buttons, @charlesbetros @quajak thoughts?

2021-10-17 07:32 UTC, quajak commented
I think currently the best way would be to set a flag in the mouse driver, which normally is disabled.

2021-11-07 23:53 UTC, MishaTY commented
Not needed anymore because of #1989 which allows to disable the scroll wheel.

2021-11-07 23:53 UTC, closed without merging