Update DevKit.md
CosmosOS/Cosmos pull request #2198
Opened 2022-04-23 22:47 UTC by jackbielinski

Added installation instructions for VS2022

2022-04-23 22:51 UTC, zarlo commented
you should merge it in to the VS2022 branch (https://github.com/CosmosOS/Cosmos/pull/2009)

2022-05-02 16:24 UTC, ptobuon commented on Docs/articles/Installation/DevKit.md
>     * When following the tutorial, replace *OctoCat* with *CosmosOS* and *Spoon-Knife* with *Cosmos*.
This can be removed.

2022-05-02 16:32 UTC, ptobuon requested changes
There is only a suggested change. The rest is good.

2022-05-04 12:19 UTC, MishaTY requested changes

2022-05-04 12:19 UTC, MishaTY commented on Docs/articles/Installation/DevKit.md
> +* When the installation is complete, Visual Studio will automatically open and you may begin programming with your new, modified copy of Cosmos.
This is no longer true, visual studio does not open after installation

2022-05-04 12:19 UTC, MishaTY commented on Docs/articles/Installation/DevKit.md
>     * When following the tutorial, replace *OctoCat* with *CosmosOS* and *Spoon-Knife* with *Cosmos*.
This can be removed

2022-05-31 22:09 UTC, valentinbreiz commented
Since VS2022 is merged in master, just use the master branch and install the devkit

2022-05-31 22:09 UTC, closed without merging