Add arc drawing to canvas
CosmosOS/Cosmos pull request #2421
Opened 2022-09-29 21:56 UTC by terminal-cs

[+] Added arc drawing (Resolves #1639)

2022-09-29 22:16 UTC, quajak requested changes
Looks good. Before I merge, can you please add a test usage to the CGS test kernel?

2022-09-29 23:10 UTC, terminal-cs commented
> Looks good. Before I merge, can you please add a test usage to the CGS test kernel?

May i ask where that is?

2022-09-30 21:06 UTC, MishaTY commented
> > Looks good. Before I merge, can you please add a test usage to the CGS test kernel?
> 
> May i ask where that is?

https://github.com/CosmosOS/Cosmos/blob/master/Tests/Kernels/GraphicTest/Kernel.cs

2022-10-05 17:42 UTC, quajak approved these changes

2022-10-05 18:54 UTC, merged