Add a constructor than picks int[] arrays.
CosmosOS/Cosmos pull request #2429
Opened 2022-10-06 19:17 UTC by RaphMar2021

Added a constructor than picks int[] arrays.

2022-10-07 00:40 UTC, quajak requested changes
Thanks for the contribution!

2022-10-07 00:40 UTC, quajak commented on source/Cosmos.System2/Graphics/Bitmap.cs
> +        public Bitmap(uint Width, uint Height, int[] pixelData, ColorDepth colorDepth) : base(Width, Height, colorDepth)
Please add documentation to the function call. I also dont think this function call needs ColorDepth and can always use ColorDepth32

2022-11-30 17:15 UTC, TheFocusMan commented
This PR is old

2022-11-30 17:16 UTC, RaphMar2021 commented
i don't care

2022-11-30 17:16 UTC, RaphMar2021 commented
@TheFocusMan

2022-11-30 17:17 UTC, TheFocusMan commented
> i don't care

Why is not approved yet?

2022-11-30 17:18 UTC, RaphMar2021 commented
idk
ping a coredev on cosmos discord because i left it

2022-11-30 17:20 UTC, TheFocusMan commented
Bro u should to request review and i am not even in the discord server

2022-11-30 17:21 UTC, RaphMar2021 commented
bye

2022-11-30 17:21 UTC, closed without merging