Minor heap changes, Realloc function
CosmosOS/Cosmos pull request #2430
Opened 2022-10-06 23:49 UTC by terminal-cs

2022-10-07 00:05 UTC, zarlo commented
have you been reading my mind?

well at lest i can remove this from what im working on

2022-10-07 00:33 UTC, terminal-cs commented
> have you been reading my mind?
> 
> well at lest i can remove this from what im working on

I guess so lol

2022-10-07 00:36 UTC, quajak requested changes
Good idea! Could you please add a test somewhere to ensure that this does what its supposed to do and does not mess with the garbage collector? 

Regarding the garbage collecting, this change does not really work well with C# objects since all reference to the original object would be broken. This means that either we dont allow this for objects with references pointing to it or its the users fault.  Since we cant accurately detect if something is being referenced (if the reference is not static), I would recommend we go with option 2 but include a large warning.

Would be great if you can also add a sentence to the documentation.

2022-10-07 00:36 UTC, quajak commented on source/Cosmos.Core/Memory/Heap.cs
> +		/// Re-allocates or "re-sizes" data asigned to a pointer.
Maybe add that this must be a pointer to the start of the allocated memory region

2022-10-07 00:36 UTC, quajak commented on source/Cosmos.Core/Memory/Heap.cs
> +        public static byte* Realloc(byte* aPtr, uint NewSize)
Typo: newSize not NewSize

2022-10-07 00:36 UTC, quajak commented on source/Cosmos.Core/Memory/Heap.cs
> +            ((ushort*)ToReturn)[-1] = ((ushort*)aPtr)[-1];
I have thought about this more and it seems like we should just set the GC state to 0 for the new object, since the old references no longer count.

2022-10-07 01:33 UTC, quajak approved these changes

2022-10-07 01:49 UTC, quajak approved these changes

2022-10-09 21:23 UTC, quajak approved these changes

2022-10-09 21:23 UTC, merged