Update docs for vs2022
CosmosOS/Cosmos pull request #2514
Opened 2022-12-18 20:33 UTC by MishaTY

2022-12-18 20:33 UTC, Kiirx commented
you forgot the bottom

2022-12-18 20:35 UTC, AnErrupTion requested changes
You forgot to change the references of "install-VS2019.bat" to "install-VS2022.bat"

2022-12-18 20:39 UTC, Kiirx requested changes

2022-12-18 20:39 UTC, Kiirx commented on Docs/articles/Installation/DevKit.md
>  ## Arguments for the 'install-VS2019.bat' file
VS2022

2022-12-19 00:35 UTC, quajak approved these changes

2022-12-19 02:02 UTC, merged