fix acpi overlapping
CosmosOS/Cosmos pull request #2550
Opened 2023-01-06 03:23 UTC by AsertCreator

it should work but i didnt test yet and dont now how. well i fixed acpi table overlapping by making memory allocator to not allocate "unusable" addresses. push to feature/apic. 

fixes #2546

2023-01-06 03:24 UTC, AsertCreator commented
hmm, why appveyor test doesnt start?

2023-01-06 03:51 UTC, terminal-cs commented
> hmm, why appveyor test doesnt start?

Because you aren't pushing to the main branch

2023-01-06 04:02 UTC, AsertCreator commented
oh okay

2023-01-09 09:14 UTC, valentinbreiz commented
Thanks for the fix it could be merged if working but it's a tricky way to work around the bug... the actual reason why ACPI tables can be overwritten is because the multiboot2 memory map is kind of broken

2023-01-10 06:19 UTC, AsertCreator commented
oh when i run it in appveyor kernel crashes after ps/2 controller initialization

2023-01-13 15:46 UTC, TheFocusMan commented
> oh when i run it in appveyor kernel crashes after ps/2 controller initialization

yep it is happen to me too in Fat File Test it is can be beacuse the py.yml, before the file added appveyor want stop on timeout

2023-01-14 00:34 UTC, AsertCreator commented
> > oh when i run it in appveyor kernel crashes after ps/2 controller initialization
> 
> yep it is happen to me too in Fat File Test it is can be beacuse the py.yml, before the file added appveyor want stop on timeout

apparently it says that kernel crashed at nullreferenceexception. maybe something wrong with bochs? cause it works on vmware and qemu. or maybe it didnt get enough memory and RAT just overwritten acpi tables or something? it means we need to give bochs more memory.

2023-01-14 21:35 UTC, quajak commented
> > > oh when i run it in appveyor kernel crashes after ps/2 controller initialization
> > 
> > 
> > yep it is happen to me too in Fat File Test it is can be beacuse the py.yml, before the file added appveyor want stop on timeout
> 
> apparently it says that kernel crashed at nullreferenceexception. maybe something wrong with bochs? cause it works on vmware and qemu. or maybe it didnt get enough memory and RAT just overwritten acpi tables or something? it means we need to give bochs more memory.

Can you check the map file for in which method it crashes with the null reference exception? We shouldnt be running into memory issues

2023-01-15 02:05 UTC, AsertCreator commented
```024a3771 l       .text	00000000 SystemInt32SystemCollectionsGenericEqualityComparer1CosmosHALPCIDeviceIndexOfCosmosHALPCIDevicearrayCosmosHALPCIDeviceSystemInt32SystemInt32.IL_0012.AfterAddressCheck```
its should be it. i cant understand how il2cpu encodes method names but i can tell that something is for `EqualityComparer`

2023-02-03 16:18 UTC, MishaTY requested changes

2023-02-04 10:38 UTC, AsertCreator commented on Build/limine/boot/limine.cfg
> +DEFAULT_ENTRY=1
i did this with rebase. virtually, there are changes. practically there are no new changes

2023-03-30 02:16 UTC, AsertCreator commented
okay, this wont work. if someone has time, please fix this

2023-03-30 02:16 UTC, closed without merging