Plug ToArgb()
CosmosOS/Cosmos pull request #2710
Opened 2023-06-18 15:32 UTC by valentinbreiz

2023-06-18 15:35 UTC, terminal-cs commented
Was it not working before already?

2023-06-19 10:37 UTC, valentinbreiz commented
@quajak this fixes the memory leaks issue + boost FPS

2023-06-19 13:32 UTC, valentinbreiz commented on source/Cosmos.System2_Plugs/System/Drawing/ColorImpl.cs
> +            aKnownColor = (short)knownColor;
I think we should let it to prevent breaks in other methods. The only thing that really changes is the way we get_Value()

2023-09-06 06:10 UTC, cameronos commented
Any chance of this getting pushed to the master?

2023-09-25 15:58 UTC, quajak requested changes
Looks good except for that one change

2023-09-25 15:58 UTC, quajak commented on source/Cosmos.System2/Graphics/Canvas.cs
> +        internal int xBytePerPixel;
Can you make the naming scheme uniform?

2023-09-27 13:33 UTC, quajak approved these changes

2023-09-27 14:10 UTC, merged