Add Object.ToString
CosmosOS/Cosmos pull request #2714
Opened 2023-06-21 10:21 UTC by GoldenretriverYT

Adds a small Object.ToString implementation that shows
<object of TYPENAME>

so like
<object of EventArgs>

2023-06-21 17:17 UTC, jvyden requested changes
.NET itself just returns the name directly in this scenario, no surrounding text. I think it would be much better if you modified it to be consistent with .NET here.

2023-06-22 14:58 UTC, quajak commented
> .NET itself just returns the name directly in this scenario, no surrounding text. I think it would be much better if you modified it to be consistent with .NET here.

I think thats a good idea

2023-06-24 00:06 UTC, jvyden approved these changes

2023-06-25 16:25 UTC, quajak approved these changes

2023-06-25 16:53 UTC, merged