Adjust COSMOS documentation
CosmosOS/Cosmos pull request #2990
Opened 2024-03-17 18:02 UTC by cameronos

This should clean majority of the documentation on cosmosos.github.io to ensure clarity and for it to be up-to-date. Some articles (like the Levels.md) aren't touched because they are quite old.

2024-03-17 18:39 UTC, 9xbt commented
I'd add a "Last updated [date]" paragraph at the end of every page of the docs so we can know if a page is outdated or not

2024-03-17 18:44 UTC, cameronos commented
> I'd add a "Last updated [date]" paragraph at the end of every page of the docs so we can know if a page is outdated or not

Awesome, thanks much

2024-03-18 03:46 UTC, zarlo requested changes

2024-03-18 03:46 UTC, zarlo commented on Docs/articles/Kernel/VFS.md
> +In this article, we will discuss about using Cosmos VFS (virtual file system).\
is the \ here in error?

2024-03-18 04:02 UTC, cameronos commented on Docs/articles/Installation/DevKit.md
> +* Git clone the current source code of Cosmos and rename the folder to simply 'Cosmos'.
Oh, yeah, that makes total sense. My fault. Will fix this

2024-03-18 04:03 UTC, cameronos commented on Docs/articles/Kernel/CGS.md
> +```CSharp
Are we able to provide any modes preset for the documentation, or is it better to leave blank?

2024-03-18 04:03 UTC, cameronos commented on Docs/articles/Kernel/VFS.md
> +In this article, we will discuss about using Cosmos VFS (virtual file system).\
I'm trying to new line, I think..?

2024-03-18 04:09 UTC, zarlo commented on Docs/articles/Kernel/CGS.md
> +```CSharp
they should be in the api docs i know it is for some of the back ends

maybe something like "Some modes currently available are as follows (Depends on the backend used)"

2024-03-18 18:07 UTC, PratyushKing commented on Docs/articles/Installation/DevKit.md
> +* Git clone the current source code of Cosmos and rename the folder to simply 'Cosmos'.
> if you git clone you dont need to rename the folder

wait but isnt some people clone the "Cosmos-master" and then git clone saves it as that cuz it just stores the repo name cloned in the URL?

2024-03-24 16:33 UTC, cameronos commented
I've adjusted the concerns and added a _Last updated on [date]_  on each page to ensure continuity. Let me know how it is

2024-03-28 22:56 UTC, zarlo approved these changes

2024-04-01 02:27 UTC, cameronos commented
Can anyone go and push this through? Thanks

2024-04-15 04:26 UTC, merged